name: Build WSA
on:
  workflow_dispatch:

    inputs:
      arch:
        description: 'Architecture:'
        required: true
        default: 'x64'
        type: choice
        options:
          - 'x64'
          - 'ARM64'
      release_type:
        description: 'Release Channel:'
        required: true
        default: 'Release Preview'
        type: choice
        options:
          - 'General Availability'
          - 'Release Preview'
          - 'Beta'
          - 'Dev'
      gapps_brand:
        description: 'GApps Brand:'
        required: true
        default: 'MindTheGapps'
        type: choice
        options:
          - 'None'
          - 'MindTheGapps'
      root_ver:
        description: 'Root Solution:'
        required: true
        default: 'Magisk (Stable)'
        type: choice
        options:
          - 'None'
          - 'KernelSU'
          - 'Magisk (Stable)'
          - 'Magisk (Beta)'
          - 'Magisk (Canary)'
          - 'Magisk (Debug)'
          - 'Magisk Delta (Canary)'
      remove_amazon:
        description: 'Remove Amazon Appstore'
        required: true
        default: true
        type: boolean
      Compression:
        description: 'Compression Format:'
        required: true
        default: '*.zip (Fast)'
        type: choice
        options:
          - '*.zip (Fast)'
          - '*.7z (Ultra)'

permissions:
  contents: write
  actions: write

jobs:
  Build-WSA:
    name: Build WSA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LSPosed/MagiskOnWSALocal
          path: MagiskOnWSALocal

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setools qemu-utils ca-certificates lzip patchelf e2fsprogs python3 python3-pip aria2 p7zip-full attr xz-utils unzip
          python3 -m pip install requests -v

      - name: Build WSA
        id: build_wsa
        working-directory: MagiskOnWSALocal
        run: |
          declare -A opts=(
            ["ARCH,x64"]="x64"
            ["ARCH,ARM64"]="arm64"
            ["RELEASE_TYPE,General Availability"]="retail"
            ["RELEASE_TYPE,Release Preview"]="RP"
            ["RELEASE_TYPE,Beta"]="WIS"
            ["RELEASE_TYPE,Dev"]="WIF"
            ["ROOT_VER,Magisk Delta (Canary)"]="--magisk-custom"
            ["ROOT_VER,None"]="--root-sol none"
            ["ROOT_VER,KernelSU"]="--root-sol kernelsu"
            ["ROOT_VER,Magisk (Stable)"]="--magisk-ver stable"
            ["ROOT_VER,Magisk (Beta)"]="--magisk-ver beta"
            ["ROOT_VER,Magisk (Canary)"]="--magisk-ver canary"
            ["ROOT_VER,Magisk (Debug)"]="--magisk-ver debug"
            ["GAPPS_BRAND,MindTheGapps"]="MindTheGapps"
            ["GAPPS_BRAND,None"]="none"
            ["REMOVE_AMAZON,true"]="--remove-amazon"
            ["COMPRESSION,*.zip (Fast)"]="zip"
            ["COMPRESSION,*.7z (Ultra)"]="7z"   
          )
      
          if [[ "${{ inputs.root_ver }}" == "Magisk Delta (Canary)" ]]; then
            aria2c -d ./download -o magisk-stable.zip https://huskydg.github.io/magisk-files/app-release.apk
          fi

          scripts/build.sh \
            --arch ${opts[ARCH,${{ inputs.arch }}]} \
            --release-type ${opts[RELEASE_TYPE,${{ inputs.release_type }}]} \
            ${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]} \
            ${opts[ROOT_VER,${{ inputs.root_ver }}]} \
            --gapps-brand ${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]}

          echo "compression=${opts[COMPRESSION,${{ inputs.compression }}]}" >> $GITHUB_OUTPUT
          echo "arch=${opts[ARCH,${{ inputs.arch }}]}" >> $GITHUB_OUTPUT
          echo "wsa_name=$(basename ./output/*)" >> $GITHUB_ENV

      - name: Getting WSA version tag
        run: |
          regex="WSA_(.*)_${{ steps.build_wsa.outputs.arch }}"
          if [[ '${{ env.wsa_name }}' =~ $regex ]]; then
            echo "wsaver=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "wsaver=WSA" >> $GITHUB_ENV
          fi

      - name: Archiving and compressing artifact
        working-directory: MagiskOnWSALocal/output
        run: |
          if [[ "${{ inputs.compression }}" == "*.zip (Fast)" ]]; then
            7z a -tzip -mmt104 -mx4 -bb2 -saa *
          fi
          if [[ "${{ inputs.compression }}" == "*.7z (Ultra)" ]]; then
            7z a -t7z -m0=lzma2 -mx9 -mmt104 -saa *
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: 'MagiskOnWSALocal/output/${{ env.wsa_name }}.${{ steps.build_wsa.outputs.compression }}'
          tag_name: WSA-${{ env.wsaver }}
          name: WSA ${{ env.wsaver }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
